from traceback import print_tb

responce = {"firmwares": {"main": "5.58.5.15", "test": "0.1.1"},
            "test_times": [["QR code verification", 0.001], ["Sensor ID verification", 5.19],
                           ["Stand firmware check", 33.459], ["Stand calibration", 0.066],
                           ["Reverse polarity protection check", 0.075], ["Device smoke test", 0.826],
                           ["Obtaining FCTFW for the device", 3.222], ["Obtaining firmware for the device", 3.014],
                           ["MCU programming", 38.13], ["Device initialization", 1.289], ["LED's check", 0.545],
                           ["MCU battery meter check", 0.093], ["MCU temperature sensor check", 0.019],
                           ["Motion sensor check", 17.463], ["Radio module calibration and check", 3.065],
                           ["Clock generator check", 3.067], ["Button check", 3.101],
                           ["Disabled device consumption check", 5.273], ["Adding information to the firmware", 0.027],
                           ["MCU programming", 34.799]], "description": {"color": "white"},
            "test_results": [{"name": "Color", "pass": True, "value": "white", "max_thr": "", "min_thr": ""},
                             {"name": "Device ID", "pass": True, "value": "77FC257D", "max_thr": "", "min_thr": ""},
                             {"name": "U key out", "pass": True, "value": "0.002 V", "max_thr": "0.3",
                              "min_thr": "-0.1"},
                             {"name": "Current consumption", "pass": True, "value": "5052 µA", "max_thr": "40000",
                              "min_thr": "0"},
                             {"name": "MCU supply voltage", "pass": True, "value": "2.994 V", "max_thr": "3.4",
                              "min_thr": "2.9"},
                             {"name": "Launch time, s", "pass": True, "value": "0.2", "max_thr": "", "min_thr": ""},
                             {"name": "FCTFW version", "pass": True, "value": "0.2.8", "max_thr": "", "min_thr": ""},
                             {"name": "Green LED brightness", "pass": True, "value": "4933", "max_thr": "5500",
                              "min_thr": "3500"},
                             {"name": "Disabled LED brightness", "pass": True, "value": "0", "max_thr": "5",
                              "min_thr": "None"},
                             {"name": "Battery meter Δ", "pass": True, "value": "-3.84 mV", "max_thr": "200",
                              "min_thr": "-200"},
                             {"name": "MCU temperature", "pass": True, "value": "21 °C", "max_thr": "50",
                              "min_thr": "0"},
                             {"name": "Main out. deviations qty", "pass": True, "value": "0", "max_thr": "50",
                              "min_thr": "None"},
                             {"name": "Ref. out. deviations qty", "pass": True, "value": "0", "max_thr": "50",
                              "min_thr": "None"},
                             {"name": "LPF activations qty", "pass": True, "value": "0", "max_thr": "5",
                              "min_thr": "None"},
                             {"name": "HPF activations qty.", "pass": True, "value": "0", "max_thr": "5",
                              "min_thr": "None"},
                             {"name": "RFM frequency deviation", "pass": True, "value": "-146 Hz", "max_thr": "500",
                              "min_thr": "-500"},
                             {"name": "RFM transmission RSSI", "pass": True, "value": "-37.0 dBA", "max_thr": "None",
                              "min_thr": "-87"},
                             {"name": "RFM reception RSSI", "pass": True, "value": "-47.0 dBA", "max_thr": "None",
                              "min_thr": "-70"},
                             {"name": "Antenna 1 power level", "pass": True, "value": "0.706 dBm", "max_thr": "11",
                              "min_thr": "-3.75"},
                             {"name": "Clocking Δ", "pass": True, "value": "0 ppm", "max_thr": "25", "min_thr": "-25"},
                             {"name": "Sleep mode current", "pass": True, "value": "4.0 µA", "max_thr": "55",
                              "min_thr": "0"},
                             {"name": "Mcu UID", "pass": True, "value": "3332470c3831333630002300", "max_thr": "",
                              "min_thr": ""}], "total_time_spent": 152.72400000000002,
            "firmware_statuses": {"main": "archive", "locker": "release", "unlocker": "release"}}
print(responce["test_results"][1]["value"])